#!/usr/bin/env bash
# Registers the eve-control MCP with Relay — the SECOND of eve's two relay
# registrations. `npm run register:service` registers the eve service itself;
# this registers the MCP that lets an LLM open/close/refresh image tabs in eve.
#
# eve-control is intrinsic to eve (mcp/main.js). Relay spawns it, so we hand it
# eve's loopback internal URL + a shared secret here; eve's server validates the
# same secret on /internal/ui-command. Re-running is an idempotent upsert.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EVE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$EVE_ROOT/.env"
MCP_ENTRY="$EVE_ROOT/mcp/main.js"
RELAY="${RELAY_BIN:-/Applications/Relay.app/Contents/MacOS/relay}"

if [ ! -x "$RELAY" ]; then
  echo "Relay not found at $RELAY (set RELAY_BIN to override). Skipping eve-control MCP registration." >&2
  exit 1
fi
if [ ! -f "$MCP_ENTRY" ]; then
  echo "MCP entry not found at $MCP_ENTRY" >&2
  exit 1
fi
if [ ! -f "$ENV_FILE" ]; then
  echo "No $ENV_FILE — copy .env.example to .env first (eve loads it via --env-file=.env)." >&2
  exit 1
fi

# Read a KEY's value from .env (last definition wins); empty if absent.
env_get() { grep -E "^$1=" "$ENV_FILE" | tail -n1 | cut -d= -f2- || true; }

# Shared secret: eve's server (via .env) and this MCP (via relay --env) must use
# the same value. Generate a stable one on first run and persist it to .env.
SECRET="$(env_get EVE_INTERNAL_SECRET)"
if [ -z "$SECRET" ]; then
  SECRET="$(openssl rand -hex 32)"
  {
    printf '\n# Shared secret for the loopback /internal/ui-command endpoint that the\n'
    printf '# eve-control MCP calls. Auto-generated by scripts/register-mcp.sh; keep private.\n'
    printf 'EVE_INTERNAL_SECRET=%s\n' "$SECRET"
  } >> "$ENV_FILE"
  echo "Generated EVE_INTERNAL_SECRET and appended it to .env"
fi

# Internal endpoint = the loopback-only HTTP listener. Under DUAL_LISTEN that's
# HTTP_PORT; for a plaintext single listener it's PORT. Default 3000. An explicit
# EVE_INTERNAL_URL in .env wins.
INTERNAL_URL="$(env_get EVE_INTERNAL_URL)"
if [ -z "$INTERNAL_URL" ]; then
  PORT_RESOLVED="$(env_get HTTP_PORT)"
  [ -z "$PORT_RESOLVED" ] && PORT_RESOLVED="$(env_get PORT)"
  [ -z "$PORT_RESOLVED" ] && PORT_RESOLVED="3000"
  INTERNAL_URL="http://127.0.0.1:$PORT_RESOLVED"
fi

# Resolve node to an absolute path: Relay is a GUI app and may not have nvm's
# node on PATH when it later respawns the MCP (same reasoning as fsMCP/build.sh).
NODE_BIN="$(command -v node || true)"
if [ -z "$NODE_BIN" ]; then
  echo "node not found on PATH" >&2
  exit 1
fi

echo "Registering eve-control MCP (url=$INTERNAL_URL, entry=$MCP_ENTRY)"
"$RELAY" mcp register \
  --name eve-control \
  --id relay-eve-control \
  --command "$NODE_BIN" \
  --args "$MCP_ENTRY" \
  --env "EVE_INTERNAL_URL=$INTERNAL_URL" \
  --env "EVE_INTERNAL_SECRET=$SECRET"
echo "Registered eve-control MCP with Relay (add it to a project's Allowed MCPs to use it)."
